# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
