# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpsapp', '0004_wheel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wheel',
            table='wheel',
        ),
    ]
