# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpsapp', '0005_auto_20190112_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='trackid',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
