# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpsapp', '0007_auto_20190116_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='num',
        ),
    ]
