# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpsapp', '0008_remove_detail_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='img',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
